name: 'Dependabot Labeler'
description: 'Add labels to dependabot pull request'
inputs:
  GITHUB_TOKEN:  # id of input
    description: 'the github token'
    required: true
  dependabot-metadata:
    description: 'the metadata from the depenabot pull request'
runs:
  using: "composite"
  steps:
    - name: Dependabot metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v1.3.3
    - name: Create label
      shell: bash
      run: |
        gh label create minor-version --description "a minor version is waiting for an upgrade" --color 0E8A16 --force
        gh label create patch-version --description "a patch version is waiting for an upgrade" --color 1D76DB --force
        gh label create major-version --description "a major version is waiting for an upgrade" --color D93F0B --force
        gh label create development-update --description "a development dependency is waiting for an upgrade" --color 0E8A16 --force
        gh label create production-update --description "a production dependency is waiting for an upgrade" --color B60205 --force
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
    - name: Label minor updates
      if: ${{steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor'}}
      shell: bash
      run: gh pr edit $PR_URL --add-label "minor-version"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
    - name: Label patch updates
      if: ${{steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'}}
      shell: bash
      run: gh pr edit $PR_URL --add-label "patch-version"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
    - name: Label major updates
      if: ${{steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major'}}
      shell: bash
      run: gh pr edit $PR_URL --add-label "major-version"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
    - name: Label development dependencies updates
      if: ${{steps.dependabot-metadata.outputs.dependency-type == 'direct:development'}}
      shell: bash
      run: gh pr edit $PR_URL --add-label "development-update"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
    - name: Label development dependencies updates
      if: ${{steps.dependabot-metadata.outputs.dependency-type == 'direct:production'}}
      shell: bash
      run: gh pr edit $PR_URL --add-label "production-update"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
